# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4e2aa4878a444f6eab629a8f3e9b4e7d3f2c43d2e8058ff2518f8fa704018d8509a28f5b50819ce369b6c349c6b2fa3d5733ced6eb10be609bb8a3f3ef887e1

test:
  secret_key_base: 56e5d832cf9703f03b9130e92e4c84c7ed5d7d1e53a76671b0c079446a5053b2d9fdbb823360cc9992031716e9e9ba61395843aef55010c031215853645b3f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
